server:
  port: 9001
spring:
  profiles:
    active: mongodb,commons
  application:
    name: hotProduct
eureka:
  client:
    service-url:
      defaultZone: http://10.211.55.6:8761/eureka
  instance:
    prefer-ip-address: true # 优选IP作为服务的注册、发现、访问地址。