spring:
  data:
    mongodb:
#      host: 10.211.55.6
#      port: 27017
#      username: john
#      password: john
#      authentication-database: admin
#      database: livegoods
      uri: mongodb://john:john@10.211.55.6:27017/livegoods


