search:
  init:
    enable: true
spring:
  profiles:
    active: mongodb,commons
  application:
    name: search
  elasticsearch:
    rest:
      uris: http://10.211.55.6:9200,http://10.211.55.5:9200
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://10.211.55.6:8761/eureka
  instance:
    prefer-ip-address: true